language: c
before_script:
  - chmod a+x ndk.sh
  - ./ndk.sh
  - ./android-configure android-ndk-r10e
  
script: make CFLAGS+='-std=c99'

after_success:
  - ls out
  - curl -H "Authorization: Bearer $ACCESS_TOKEN" https://api-content.dropbox.com/1/files_put/auto/ -T /home/travis/build/geeteshk/node/node
