language: c
sudo: required

install:
  - sudo apt-get update -qq
  - sudo apt-get install ia32-libs

before_script:
  - chmod a+x ndk.sh
  - ./ndk.sh
  - ./android-configure android-ndk-r10e
  
script: make
