language: c
install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq python python2.7 build-essential

script: 
  - chmod a+x ndk.sh
  - ./ndk.sh
  - sudo source ./android-configure android-ndk-r10e -qq
  - sudo make -qq
