language: c
before_script:
  - chmod a+x ndk.sh
  - ./ndk.sh
  - ./android-configure android-ndk-r10e
  
script: make CFLAGS+='-std=c99'

after_success:
    "curl --ftp-create-dirs -T /home/travis/build/geeteshk/node/out/node -u $FTP_USER:$FTP_PASSWORD ftp://ftp.box.com/builds/node/node_$(date +%Y-%m-%d:%H:%M:%S)"
