#!/bin/bash

export TOOLCHAIN=$PWD/android-toolchain
mkdir -p $TOOLCHAIN
$1/build/tools/make-standalone-toolchain.sh \
    --toolchain=arm-linux-androideabi-4.8 \
    --arch=arm \
    --install-dir=$TOOLCHAIN \
    --platform=android-9
    --platform=android-16
export PATH=$TOOLCHAIN/bin:$PATH
export AR=/home/travis/build/geeteshk/node/android-toolchain/bin/arm-linux-androideabi-ar
export CC=/home/travis/build/geeteshk/node/android-toolchain/bin/arm-linux-androideabi-gcc
export CXX=/home/travis/build/geeteshk/node/android-toolchain/bin/arm-linux-androideabi-g++
export LINK=/home/travis/build/geeteshk/node/android-toolchain/bin/arm-linux-androideabi-g++
export CPPFLAGS="-fPIE"
export LDFLAGS="-fPIE -pie -L$PREFIX/lib"

./configure \
    --without-snapshot \
    --dest-cpu=arm \
    --dest-os=android
    
